### PR TITLE
add support for uds_windows (Unix domain sockets for Windows 10 build…

### PR DESCRIPTION
**Pull request by moh-eulith**
… 1809, release in 2018, and above)

### CODE REVIEW

**Comment by moh-eulith** [comment]
Fixed formatting.

**Comment by notgull** [comment]
In my opinion, dealing with socket types not in the standard library is out of the scope for `async-io`.

**Comment by moh-eulith** [comment]
@notgull I respectfully disagree. I wasn't trying to set a new precedent here. Just look at the existing Cargo.toml:

```
[target."cfg(unix)".dependencies]
libc = "0.2.77"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winsock2"] }
```

Clearly, this stuff is highly OS specific, precisely because the abstraction in the Rust standard lib is rather poor. Async-io fills in that void, and is much needed and appreciated for that.

I think the result of adding this speaks for itself: tests/async.rc removes 5 lines of `#[cfg(unix)]` and therefore passes 5 tests without being tied to a particular OS.

**Comment by taiki-e** [comment]
Thanks for the PR! I would prefer not to do this in async-io, as we do not want to include third-party crates in the public API whenever possible.

However, if we can provide the same API as the Unix one, it might be ok to support this as an optional feature of async-net.

**Comment by moh-eulith** [comment]
I was trying to implement this here so it gets inherited by async-std, which is used by another project in a non-portable way.

I'll try to put all the code in async-std and go from there.

**Pull request closed without merging**
