### PR TITLE
poll_readable() and poll_writable()

### PR DESCRIPTION
**Pull request by stjepang**
Supersedes #37

@dvc94ch, I wanted to give suggestions in #37 but this feature turned out to be more complicated than I anticipated. I just went ahead and did all the refactoring that was necessary, even making it so that `AsyncRead` and `AsyncWrite` also depend on `poll_readable()` and `poll_writable()`. Wanna give this PR a try in your project that motivated #36 ?

@taiki-e, I actually decided to take `&self` rather than `&mut self` in those methods with a `# Caveat` section in the documentation that says you shouldn't use them concurrently. There's a similar documented caveat for `AsyncRead` and `AsyncWrite` too. Since `Async` is a low-level primitive, this flexibility makes it easier to build higher-level abstractions like `async-net` on top of it.

### CODE REVIEW

**Comment by dvc94ch** [comment]
Works well, thanks!

**Comment by taiki-e** [comment]
> I actually decided to take `&self` rather than `&mut self` in those methods with a `# Caveat` section in the documentation that says you shouldn't use them concurrently. There's a similar documented caveat for `AsyncRead` and `AsyncWrite` too. Since `Async` is a low-level primitive, this flexibility makes it easier to build higher-level abstractions like `async-net` on top of it.

If it's documented, I think it's okay.

By the way, does this caveat mean that the "any number of concurrent I/O operations" mentioned in https://github.com/rust-lang/futures-rs/pull/2139 is no longer supported with `AsyncRead`/`AsyncWrite`?

**Comment by stjepang** [comment]
@taiki-e Yes, that is correct.

**Comment by dvc94ch** [comment]
What's the status of this pr?

**Comment by stjepang** [comment]
Published in v1.2.0

**Pull request merged**
